### ISSUE TITLE
ORAM/Pi5 - USB C does not support midi send/receive

### ISSUE THREAD

**Issue by hlnorris3** [zynthian/zynthian-issue-tracking#1032]
On the Pi4 with 32bit os it was possible to send and receive midi over the USB C port (with appropriate splitter cable). On Pi5 ORAM this is not working. 

Connect USB C port with appropriate splitter to Pi5 and Windows PC USB port.
Hear beep from Windows acknowledging connection
Go to  Capture MIDI from on a given chain and note absent option

The (in this case) Windows host (say running Ableton or Midi-OX) sees that a USB midi port is connected and lists it as MIDI function. However the port does not appear in Zynthian "Capture MIDI from"

Latest ORAM update 4/29/24 (residing on SD card) no other storage connected
Pi5
eeprom update sat April 20

There is discussion about USB C and OTG connection problems on the Pi 5.
https://forums.raspberrypi.com/viewtopic.php?t=358573
https://github.com/raspberrypi/bookworm-feedback/issues/230

**Comment by jofemodo** [comment]
It's been fixed by https://github.com/zynthian/zynthian-ui/commit/11debac192d83edc930a82db7723a970bfdfd988

**Comment by hlnorris3** [comment]
Great - I just tested and all is good on my system. Zynthian still appears as "midi function" but that's no problem for me.
