### ISSUE TITLE
MIDI out not working.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1053]
**Describe the bug**
Qmidinet does not output MIDI data 

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Qmidinet'
3. Got To MIDI output select qmidinet

**Expected behavior**
QMIDINet should output data when enabled

**Setup:**
 Raspberry Pi 4 Model B Rev 1.4
Audio: [Behringer UMC1820]
Display: [Pi 7 Touchscreen Display 800x480]
Wiring: [MCP23017_EXTRA]
I2C: [MCP23017@0x20]
Profile: [v4_studio]

zyncoder: [oram (d25a811)]
zynthian-ui: [oram (4394601)]
zynthian-sys: [oram (e81b6db)]
zynthian-data: [oram (db0355a)]
zynthian-webconf: [oram (eb9e08d)]

**Comment by riban-bw** [comment]
It looks like an issue with using jack port alias rather than port name in the chain MIDI output routing. I need to get in a bit deeper but the midi router is not routing to the destination because it is listed as the alias. The UI is toggling the destination and storing the alias. I did change so that the alias is used throughout so that the toggle worked but it should be changed the other way. I don't have time to resolve now. I will look later. I have flagged as an Oram dependancy.

**Comment by riban-bw** [comment]
I have modified the title because it seems that many MIDI outputs are not currently working!

**Comment by riban-bw** [comment]
@jofemodo had to roll back this fix. Will review again...

**Comment by riban-bw** [comment]
A fix has been applied but adding MIDI effect fails to route output of effect. More work required.

**Comment by riban-bw** [comment]
And it is fixed... again!

**Comment by wyleu** [comment]
Still broken here...
I can see it all patched in patchage.

zyncoder: oram (a7976d8)
zynthian-ui: oram (b254907)
zynthian-sys: oram (d542728)
zynthian-data: oram (db0355a)
zynthian-webconf: oram (cce8b07)
Midi log is being remarkably quiet. I can see My 5pin MIDI coming in via the 1820, but nothing else kicks MIDI log into revealing.  sequences ain't are running but not playing a chain it's played before. The blue M is flashing appropriately.
