### ISSUE TITLE
Bug: Persistent internal total number of menu entries when changing active chain from chain menu

### ISSUE THREAD

**Issue by johannesmenzel** [zynthian/zynthian-issue-tracking#1390]
**Describe the bug**
When switching from the master bus chain menu to another chain menu by arrow keys left/right, there is a limited number of reachable menu entries in the latter menu. It seems like the internal number of menu entries persists, so when trying to navigate the menu (by encoder 4 or arrow keys up/down) the cursor stops presumably at the entry with the number of total entries in the first menu.

**To Reproduce**
1. select master chain
2. go to chain menu by clicking the opt button
3. navigate to the chain menu of another track by arrow key left
4. navigate down thorugh the menu by encoder 4 or arrow key down
5. navigation stops at a specific entry (possibly at position equally to the total number of menu entries of the master chain menu)

**Expected behavior**
Being able to navigate the entire menu

**Screenshots**
no

**Setup:**
Not at hand, but:
- latest vangelis
- custom build with 4 mcp23017 encoders, hdmi screen, v5touch control and hifiberry dac adc.

**Additional context**
It oftentimes happens to me because I tend to adjust the master volume after changes in chains. Consequently master bus becomes the active chain. Then I accidentally get to the master chain menu intending to get into an instrument chain menu in order to add an fx plugin or similar. Maybe we could prevent switching the active chain for volume changes by touch input.

**Comment by riban-bw** [comment]
I cannot reproduce this. It _may_ have been fixed in Vangelis. Please retest.

**Comment by johannesmenzel** [comment]
The issue is still persistent here. (See corresponding [thread](https://discourse.zynthian.org/t/bug-number-of-menu-items/11245/2?u=hannesmenzel))

**Comment by riban-bw** [comment]
You didn't use the, "Report Issue" link from webconf or the template in GitHub so there is missing detail, e.g. the software versions you are using. Please post a screenshot of your webconf dashboard.

The video in the forum shows encoder control. I tested with arrow keys

**Comment by johannesmenzel** [comment]
```
 ##########################       ----------------------------------------
#                          #      ZynthianOS ORAM-2505
#            ##            #      Timestamp: 2025-05-30
#      ##   #  #   ##      #      Built from RaspberryPiOS Bookworm (aarch64)
#     #  #  #  #  #  #     #      ----------------------------------------
###   #  #  #  #  #  #   ###      Kit:           Custom
#  #  #  #  #  #  #  #  #  #      Display:       Generic HDMI/DSI Display
#   ##   #  #  #  #   ##   #      Soundcard:     HifiBerry DAC+ ADC PRO
#         ##    ##         #      Wiring Layout: MCP23017_ENCODERS_V5TOUCH
#                          #      ----------------------------------------
 ##########################
                                  zynthian-ui: vangelis (8ddc27)
                                  zynthian-webconf: vangelis (f07094)
                                  zyncoder: vangelis (a03a07)
                                  zynthian-sys: vangelis (4e453b)
                                  zynthian-data: vangelis (6ac209)
                                  ---------------------------------------

Linux hannes-zynthian 6.12.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.12.47-1+rpt                                                                                                                                                                                                                                             1~bookworm (2025-09-16) aarch64

```

<img width="1144" height="471" alt="Image" src="https://github.com/user-attachments/assets/967e0d1d-2dcf-4d3f-85cc-db5965c36126" />

Yes, it's about encoder movement like mentioned in the "How to reproduce" section. I can confirm that using the arrow down key it's working

**Comment by riban-bw** [comment]
The description says encoder or arrow key, which is why I tested with arrow key. I will look at the encoder bug. Cheers!

**Comment by johannesmenzel** [comment]
You're correct.

**Comment by jofemodo** [comment]
OK! Now it's fixed in Vangelis & Zynbleton.
