### ISSUE TITLE
Removing a layer from mixer screen navigates to control screen

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#621]
**Describe the bug**
When using context menu to remove a layer from the mixer view the user is taken to the control screen which is unexpected and undesirable behaviour.

**To Reproduce**
Steps to reproduce the behaviour:
1. Highlight a layer in mixer view
2. Bold press SELECT to show context menu
3. Select "Remove Layer"

**Expected behaviour**
Layer removed and return to mixer view.

**Actual behaviour**
Layer removed but navigate to control view.

**Setup:**
Not near device but manifests in current testing branch

**Comment by jofemodo** [comment]
It should be fixed with this commit:

https://github.com/zynthian/zynthian-ui/commit/c1b462a2849a68130ef4444a089a2a23b0aa2cc0

BTW, this commit is a refactorization of the show/close screen logic, that removes the modal_screen mess and implements a proper navigation history for back-action, etc.

**Comment by riban-bw** [comment]
This is still broken under some (very common) condition:

- Add several layers
- Enter a layer control screen
- Return to Mixer screen
- Remove a layer

After accessing a layer control screen, any subsequent removal of a layer jumps to the control screen. I think it may be related to the `close_modal` being called as well as `close_screen`. I thought this fix replaced the modal thing but the two still seem to be implemented and fighting each other!

**Comment by jofemodo** [comment]
I can't reproduce this error again.  For me it's fixed.

**Comment by riban-bw** [comment]
Here is my full workflow:
- From Mixer view, bold press LAYER to show _Main Menu_
- Select _Clean All_ and confirm
- Add _New Synth Layer_ MDA DX10, MIDI CH#1, Bight E.Piano
- Bold press LAYER to show _Main Menu_
- Add _New Synth Layer_ MDA JX10, MIDI CH#2, 303 Saw Bass
- Bold press BACK to show _Mixer _ view
- Short press SELECT to show _Control_ view
- Bold press BACK to show _Mixer _ view
- Bold press SELECT to show _Layer Options_
- Select _Remove Layer_ and confirm

Expect to return to _Mixer_ view but actually return to _Control_ view of layer 1.

(The actual engines and presets do not really matter - this is the full detail of what I actually did to reproduce.)

**Comment by riban-bw** [comment]
Great! That works much better, thanks... but...

There is a related issue that I had hoped would be resolved by this fix:

Whilst within the _Control_ view, removing the layer shows the _Control_ view of the next selected layer. If you remove the last layer you are left showing a _Control_ view of no layer. Maybe a simple fix for this would be to show the _Mixer_ view after removing a layer.

Exact workflow:
- From _Mixer_ view, short press SELECT to show _Control_ view for the highlighted layer
- Bold press SELECT to show context menu
- Select _Remove Layer_ and confirm
- Repeat until all layers are removed

**Comment by jofemodo** [comment]
This should be solved now too. Please update and test.

**Comment by riban-bw** [comment]
Not quite...

If the last layer is a MIDI-FX layer then the same behaviour, i.e. it shows the empty control screen after remove last MIDI-FX layer.

Sorry!

**Comment by riban-bw** [comment]
Exact reproducible workflow:
- From _Mixer_ view bold press LAYER to show _Main_ menu
- Select _Clean All_ and confirm
- Select _Add New MIDI-FX Layer_, MIDI CC Map, MIDI CH#1
- Bold press SELECT to show _Layer Options_ menu
- Select _Remove Layer_ and confirm

**Comment by jofemodo** [comment]
Try now!! You made me sweat!!! ;-DD

**Comment by riban-bw** [comment]
Yay! We made it :-)

Thanks for persevering. It now works as expected. (I would have preferred it to drop back to mixer view after removing layer but accept your preference. We can't have everything our own way ;-) !)

**Comment by jofemodo** [comment]
If you open the layer options from mixer, it comes back to mixer, if you open from control, it backs to control. I think it's coherent.
