### ISSUE TITLE
Cannot add ModUI layer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#649]
**Describe the bug**
Attempt to add Mod-UI results in blank screen and inability to connect via web interface.

**To Reproduce**
1. Clean All
2. New Special Layer
3. MOD-UI - Plugin Host

**Expected behaviour**
MOD-UI is added and accessible from web browser.

**Actual behaviour**
Blank screen. Can't access mixer view. MOD-UI not accessible from web browser.

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: [HifiBerry DAC+ ADC PRO](http://192.168.8.230/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.8.230/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.8.230/hw-wiring)
I2C: [MCP23017@0x20](http://192.168.8.230/hw-wiring)
Profile: [z2_v1](http://192.168.8.230/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 30% (278M/923M)
SD Card: 60% (16G/29G)
Temperature: 55.8ºC
Overclock: [Disabled](http://192.168.8.230/hw-options)
- MIDI
Profile: [default.sh](http://192.168.8.230/ui-midi-options)
Tuning: [440 Hz](http://192.168.8.230/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.8.230/ui-midi-options)
ZS3 Sub-SnapShots: [Off](http://192.168.8.230/ui-midi-options)
MIDI to Output: [On](http://192.168.8.230/ui-midi-options)
Master Channel: [off](http://192.168.8.230/ui-midi-options)
- SOFTWARE
zyncoder: [testing (e236925)](https://github.com/zynthian/zyncoder/commit/e2369251a5456539c8d79e218c8e096accfe0f54)
zynthian-ui: [masterfx (727a4f6)](https://github.com/zynthian/zynthian-ui/commit/727a4f6e506866ad792028ecf5b50d300b5fc25c)
zynthian-sys: [testing (a5e66e4)](https://github.com/zynthian/zynthian-sys/commit/a5e66e4a9119d6ad2504bf78f774fcf33eb4d2fa)
zynthian-data: [testing (10e1f9f)](https://github.com/zynthian/zynthian-data/commit/10e1f9f0e3da196775bda4b8c6fd54a425c3e65c)
zynthian-webconf: [testing (729cc9b)](https://github.com/zynthian/zynthian-webconf/commit/729cc9b4113fd53cea512709028969d389a7d7af)

**Additional context**
Log errors:
```
Apr 27 07:53:10 zynthian startx[23193]: ERROR:zynthian_gui_layer.add_layer_midich: unsupported operand type(s) for +: 'NoneType' and 'int'
Apr 27 07:53:10 zynthian startx[23193]: ERROR:zynthian_gui.zyncoder_read: unsupported operand type(s) for +: 'NoneType' and 'int'
Apr 27 07:53:10 zynthian startx[23193]: Traceback (most recent call last):
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 366, in add_layer_midich
Apr 27 07:53:10 zynthian startx[23193]:     self.zyngui.show_screen_reset('audio_mixer')
Apr 27 07:53:10 zynthian startx[23193]:   File "./zynthian_gui.py", line 680, in show_screen_reset
Apr 27 07:53:10 zynthian startx[23193]:     self.show_screen(screen, hmode=zynthian_gui.SCREEN_HMODE_RESET)
Apr 27 07:53:10 zynthian startx[23193]:   File "./zynthian_gui.py", line 668, in show_screen
Apr 27 07:53:10 zynthian startx[23193]:     self.screens[screen].show()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 737, in show
Apr 27 07:53:10 zynthian startx[23193]:     self.refresh_visible_strips()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 849, in refresh_visible_strips
Apr 27 07:53:10 zynthian startx[23193]:     self.visible_mixer_strips[offset].set_layer(layers[index])
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 405, in set_layer
Apr 27 07:53:10 zynthian startx[23193]:     self.show()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 222, in show
Apr 27 07:53:10 zynthian startx[23193]:     self.draw()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 245, in draw
Apr 27 07:53:10 zynthian startx[23193]:     self.parent.main_canvas.itemconfig(self.legend_strip_txt, text=self.layer.midi_chan + 1)
Apr 27 07:53:10 zynthian startx[23193]: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Apr 27 07:53:10 zynthian startx[23193]: During handling of the above exception, another exception occurred:
Apr 27 07:53:10 zynthian startx[23193]: Traceback (most recent call last):
Apr 27 07:53:10 zynthian startx[23193]:   File "./zynthian_gui.py", line 1583, in zyncoder_read
Apr 27 07:53:10 zynthian startx[23193]:     self.zynswitches()
Apr 27 07:53:10 zynthian startx[23193]:   File "./zynthian_gui.py", line 1396, in zynswitches
Apr 27 07:53:10 zynthian startx[23193]:     self.zynswitch_short(i)
Apr 27 07:53:10 zynthian startx[23193]:   File "./zynthian_gui.py", line 1481, in zynswitch_short
Apr 27 07:53:10 zynthian startx[23193]:     self.screens[self.current_screen].switch_select('S')
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 294, in switch_select
Apr 27 07:53:10 zynthian startx[23193]:     self.click_listbox(None, t)
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 280, in click_listbox
Apr 27 07:53:10 zynthian startx[23193]:     self.select_action(self.index, t)
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_engine.py", line 169, in select_action
Apr 27 07:53:10 zynthian startx[23193]:     self.zyngui.screens['layer'].add_layer_engine(self.list_data[i][0], self.midi_chan)
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 309, in add_layer_engine
Apr 27 07:53:10 zynthian startx[23193]:     self.add_layer_midich(None)
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 370, in add_layer_midich
Apr 27 07:53:10 zynthian startx[23193]:     self.zyngui.show_screen_reset('audio_mixer')
Apr 27 07:53:10 zynthian startx[23193]:   File "./zynthian_gui.py", line 680, in show_screen_reset
Apr 27 07:53:10 zynthian startx[23193]:     self.show_screen(screen, hmode=zynthian_gui.SCREEN_HMODE_RESET)
Apr 27 07:53:10 zynthian startx[23193]:   File "./zynthian_gui.py", line 668, in show_screen
Apr 27 07:53:10 zynthian startx[23193]:     self.screens[screen].show()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 737, in show
Apr 27 07:53:10 zynthian startx[23193]:     self.refresh_visible_strips()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 849, in refresh_visible_strips
Apr 27 07:53:10 zynthian startx[23193]:     self.visible_mixer_strips[offset].set_layer(layers[index])
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 405, in set_layer
Apr 27 07:53:10 zynthian startx[23193]:     self.show()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 222, in show
Apr 27 07:53:10 zynthian startx[23193]:     self.draw()
Apr 27 07:53:10 zynthian startx[23193]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 245, in draw
Apr 27 07:53:10 zynthian startx[23193]:     self.parent.main_canvas.itemconfig(self.legend_strip_txt, text=self.layer.midi_chan + 1)
Apr 27 07:53:10 zynthian startx[23193]: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Apr 27 07:53:10 zynthian startx[23193]: ERROR:zynthian_engine_modui.task_websocket: Restarting MOD services ...
```

**Comment by jofemodo** [comment]
Fixed in b8821b6

**Comment by riban-bw** [comment]
Hmmm.... It took a very long time to start. Zynthian looks like it has hung. Eventually it shows errors in the log:
```
Apr 27 21:32:41 zynthian startx[1598]: ERROR:zynthian_engine_modui.api_get_request: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /reset (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x69887050>: Failed to establish a new connection: [Errno 111] Connection refused'))
Apr 27 21:32:41 zynthian startx[1598]: ERROR:zynthian_engine_modui.api_post_request: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /pedalboard/load_bundle/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x69870870>: Failed to establish a new connection: [Errno 111] Connection refused'))
Apr 27 21:32:41 zynthian startx[1598]: ERROR:zynthian_engine_modui.load_bundle: Loading Bundle /zynthian/zynthian-my-data/presets/mod-ui/pedalboards/Clavinet_AutoWah.pedalboard
Apr 27 21:32:46 zynthian startx[1598]: ERROR:zynthian_engine_modui.api_get_request: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /snapshot/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6d253bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Apr 27 21:32:46 zynthian startx[1598]: ERROR:zynthian_engine_modui.api_get_request: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /pedalpreset/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x69868d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Apr 27 21:32:46 zynthian startx[1598]: ERROR:zynthian_engine_modui.api_post_request: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /pedalpreset/enable (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6984a850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Apr 27 21:32:46 zynthian startx[1598]: ERROR:zynthian_engine_modui.api_get_request: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /pedalpreset/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x698554d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Still can't connect from web browser. No connection to audio mixer. What branch is this fix applied? (I tested on masterfx.)

**Comment by jofemodo** [comment]
I forgot to say you have to "update_zynthian.sh" because i commite a second fix on zynthian_sys, not related with the first error, but with a recent update on mod-ui/mod.host.

**Comment by jofemodo** [comment]
I'm still working on this because there are more issues with mod-ui.

**Comment by jofemodo** [comment]
I've been working on this and it's working much better now. BTW, i've improved the integration of MOD-UI with the zynmixer. Output is routed to the zynmixer return ports and the send ports are accessible from the Web GUI, so you can use MOD-UI as Main FX chain. Anyway, there is room for improvement yet and you will find the flaws for sure ;-)

**Comment by riban-bw** [comment]
Should not route arbitary sources to main return as this breaks away the normalisation from main send. I have added a 17th mixer channel for aux usage and updated the routing of mod but it would be nicer if mod were routed to the channel that it is instantiated on so that it gets a dedicated fader.

**Comment by jofemodo** [comment]
I agree. Currently we would need:

+ 16 channels for normal chains assigned to MIDI channels
+ 1 channel for MOD-UI
+ 1 channel for the Audio Player 
+ 1 channel for main

We can "force" the layer's midi_chan var. In fact we are already doing it, as the main FX-chain use midi_chan 16 (aka 17) and the Audio Player is using midi_chan 17 (aka 18). We simply would do the same with mod-ui, that is currently using midi_chan "None". Of course, in the near future, chainfication will take care of renaming "midi-chan" to "chain-num".

So chain nums (midi-chan), numberring would be, initially, like this:

+ 16 channels for normal chains assigned to MIDI channels => 0-15
+ 1 channel for main => 16
+ 1 channel for the Audio Player => 17 
+ 1 channel for MOD-UI => 18

I don't like this sorting. In the future, i would prefer to have main on 0 and assign the rest dynamically. 

Regards,

**Comment by riban-bw** [comment]
I did it a little differently. Chains 1-16 each have their own mixer channel strip with full control. Main mix bus also has its own channel strip. All other sources go to an aux mixer channel strip set to unity gain, center balanced with no controls exposed. This is channel 17. I moved main mix bus chain to channel 257 (256) which is just above the highest MIDI 2.0 channel.

A future development may be too expose separate channel strips for each source and expose the controls.

There is still some work to do on audio player which I may look at next week.

**Comment by jofemodo** [comment]
Why not havig 2 extra channels (16 & 17) so we can have MOD-UI and Audio player separated? Why not having the controls exposed so we can control volume & balance for MOD-UI and Audio Player? Having this would allow to replace Mplayer by any other audio player very quicly, as we don't need remote control for the volume anymore. We could use any command line audio player. Sox, for instance, and it would be a quick & easy change.

**Comment by riban-bw** [comment]
The idea of channel 17 was to provide an aux return to the mix bus. This is a catch-all (similar to what you tried to do with main return). I don't want to expand the mixer too much. Each additional channel adds some overhead. (If not routed then this is minimal because no audio processing occurs but there are still some extra checks done / code iterations.) I would prefer to see these two chains appear within the normal range of 1-16 or maybe we change the mixer to be more dynamic (although I don't see significant benefit in that). The current implementation shows MOD-UI on a fader strip but without the control. Shall we initially assign a (dummy) MIDI channel so it appears in the normal mixer range and review when we change to proper chain-based implementation?

MPlayer implementation was flawed and my changes have just changed the way it is broken! I suggest we move forward with chain-i-fying the audio playback. I found an audio player in the Generator Chain list but was disappointed to find out it was something that I half wrote! I will dig out the code and see if I can use sox or similar to get it going quickly.

**Comment by jofemodo** [comment]
Replacing MPlayer by Sox would be really fast, but we would need volume control in the mixer strip as we would lost the "remote volume control" we currently have with MPlayer.

**Comment by riban-bw** [comment]
Sox does not support jack.

**Comment by jofemodo** [comment]
WTF!!!! I can't believe it!! OK ... let's look for another possibility, or perhaps a combination. We could use mpg123 for compressed audio and a simpler-player for wav. Perhaps there is some Python/C library we could use instead of looking for a binary.

**Comment by jofemodo** [comment]
Now i have to disconnect to do some really boring SMD working ...

**Comment by riban-bw** [comment]
This ticket sent off at a tangent. Mod-UI should now be working but need to check it feeds mixer correctly.

**Comment by riban-bw** [comment]
Currently feeds channel 17 but without fader control. Suggest adding dedicated fader for ModUi.

**Comment by riban-bw** [comment]
I will close this issue as the original fault has been resolved. We can consider how to better present mod-ui in the mixer as a follow-on action.
